/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SupportRouteImport } from './routes/support'
import { Route as FarmersIndexRouteImport } from './routes/farmers.index'
import { Route as FarmersFarmerIdRouteImport } from './routes/farmers.$farmerId'
import { Route as MarketplaceCattleRouteImport } from './routes/marketplace.cattle'
import { Route as MarketplaceProductsRouteImport } from './routes/marketplace.products'
import { Route as OrdersCattleRouteImport } from './routes/orders.cattle'
import { Route as OrdersProductsRouteImport } from './routes/orders.products'
import { Route as SellersIndexRouteImport } from './routes/sellers.index'
import { Route as SellersSellerIdRouteImport } from './routes/sellers.$sellerId'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as VetsIndexRouteImport } from './routes/vets.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersIndexRoute = FarmersIndexRouteImport.update({
  id: '/farmers/',
  path: '/farmers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersFarmerIdRoute = FarmersFarmerIdRouteImport.update({
  id: '/farmers/$farmerId',
  path: '/farmers/$farmerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCattleRoute = MarketplaceCattleRouteImport.update({
  id: '/marketplace/cattle',
  path: '/marketplace/cattle',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProductsRoute = MarketplaceProductsRouteImport.update({
  id: '/marketplace/products',
  path: '/marketplace/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCattleRoute = OrdersCattleRouteImport.update({
  id: '/orders/cattle',
  path: '/orders/cattle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersProductsRoute = OrdersProductsRouteImport.update({
  id: '/orders/products',
  path: '/orders/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersIndexRoute = SellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSellerIdRoute = SellersSellerIdRouteImport.update({
  id: '/sellers/$sellerId',
  path: '/sellers/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const VetsIndexRoute = VetsIndexRouteImport.update({
  id: '/vets/',
  path: '/vets/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/storage': typeof StorageRoute
  '/support': typeof SupportRoute
  '/farmers/$farmerId': typeof FarmersFarmerIdRoute
  '/marketplace/cattle': typeof MarketplaceCattleRoute
  '/marketplace/products': typeof MarketplaceProductsRoute
  '/orders/cattle': typeof OrdersCattleRoute
  '/orders/products': typeof OrdersProductsRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/farmers/': typeof FarmersIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vets/': typeof VetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/storage': typeof StorageRoute
  '/support': typeof SupportRoute
  '/farmers/$farmerId': typeof FarmersFarmerIdRoute
  '/marketplace/cattle': typeof MarketplaceCattleRoute
  '/marketplace/products': typeof MarketplaceProductsRoute
  '/orders/cattle': typeof OrdersCattleRoute
  '/orders/products': typeof OrdersProductsRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/farmers': typeof FarmersIndexRoute
  '/sellers': typeof SellersIndexRoute
  '/users': typeof UsersIndexRoute
  '/vets': typeof VetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/storage': typeof StorageRoute
  '/support': typeof SupportRoute
  '/farmers/$farmerId': typeof FarmersFarmerIdRoute
  '/marketplace/cattle': typeof MarketplaceCattleRoute
  '/marketplace/products': typeof MarketplaceProductsRoute
  '/orders/cattle': typeof OrdersCattleRoute
  '/orders/products': typeof OrdersProductsRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/farmers/': typeof FarmersIndexRoute
  '/sellers/': typeof SellersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vets/': typeof VetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banners'
    | '/dashboard'
    | '/invoices'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/storage'
    | '/support'
    | '/farmers/$farmerId'
    | '/marketplace/cattle'
    | '/marketplace/products'
    | '/orders/cattle'
    | '/orders/products'
    | '/sellers/$sellerId'
    | '/users/$userId'
    | '/farmers/'
    | '/sellers/'
    | '/users/'
    | '/vets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banners'
    | '/dashboard'
    | '/invoices'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/storage'
    | '/support'
    | '/farmers/$farmerId'
    | '/marketplace/cattle'
    | '/marketplace/products'
    | '/orders/cattle'
    | '/orders/products'
    | '/sellers/$sellerId'
    | '/users/$userId'
    | '/farmers'
    | '/sellers'
    | '/users'
    | '/vets'
  id:
    | '__root__'
    | '/'
    | '/banners'
    | '/dashboard'
    | '/invoices'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/storage'
    | '/support'
    | '/farmers/$farmerId'
    | '/marketplace/cattle'
    | '/marketplace/products'
    | '/orders/cattle'
    | '/orders/products'
    | '/sellers/$sellerId'
    | '/users/$userId'
    | '/farmers/'
    | '/sellers/'
    | '/users/'
    | '/vets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannersRoute: typeof BannersRoute
  DashboardRoute: typeof DashboardRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StorageRoute: typeof StorageRoute
  SupportRoute: typeof SupportRoute
  FarmersFarmerIdRoute: typeof FarmersFarmerIdRoute
  MarketplaceCattleRoute: typeof MarketplaceCattleRoute
  MarketplaceProductsRoute: typeof MarketplaceProductsRoute
  OrdersCattleRoute: typeof OrdersCattleRoute
  OrdersProductsRoute: typeof OrdersProductsRoute
  SellersSellerIdRoute: typeof SellersSellerIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  FarmersIndexRoute: typeof FarmersIndexRoute
  SellersIndexRoute: typeof SellersIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VetsIndexRoute: typeof VetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/': {
      id: '/farmers/'
      path: '/farmers'
      fullPath: '/farmers/'
      preLoaderRoute: typeof FarmersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/$farmerId': {
      id: '/farmers/$farmerId'
      path: '/farmers/$farmerId'
      fullPath: '/farmers/$farmerId'
      preLoaderRoute: typeof FarmersFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/cattle': {
      id: '/marketplace/cattle'
      path: '/marketplace/cattle'
      fullPath: '/marketplace/cattle'
      preLoaderRoute: typeof MarketplaceCattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/products': {
      id: '/marketplace/products'
      path: '/marketplace/products'
      fullPath: '/marketplace/products'
      preLoaderRoute: typeof MarketplaceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/cattle': {
      id: '/orders/cattle'
      path: '/orders/cattle'
      fullPath: '/orders/cattle'
      preLoaderRoute: typeof OrdersCattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/products': {
      id: '/orders/products'
      path: '/orders/products'
      fullPath: '/orders/products'
      preLoaderRoute: typeof OrdersProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/': {
      id: '/sellers/'
      path: '/sellers'
      fullPath: '/sellers/'
      preLoaderRoute: typeof SellersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$sellerId': {
      id: '/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof SellersSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vets/': {
      id: '/vets/'
      path: '/vets'
      fullPath: '/vets/'
      preLoaderRoute: typeof VetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannersRoute: BannersRoute,
  DashboardRoute: DashboardRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StorageRoute: StorageRoute,
  SupportRoute: SupportRoute,
  FarmersFarmerIdRoute: FarmersFarmerIdRoute,
  MarketplaceCattleRoute: MarketplaceCattleRoute,
  MarketplaceProductsRoute: MarketplaceProductsRoute,
  OrdersCattleRoute: OrdersCattleRoute,
  OrdersProductsRoute: OrdersProductsRoute,
  SellersSellerIdRoute: SellersSellerIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  FarmersIndexRoute: FarmersIndexRoute,
  SellersIndexRoute: SellersIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VetsIndexRoute: VetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
